name: autoslicer

channels:
  - anaconda
  - conda-forge
  - defaults
  - pytorch

dependencies:
  # Core stack
  - python
  - pytorch-gpu

  # CUDA stack
#  - cudnn==8.2.1
#  - cudatoolkit==11.3.1

  # Visualization stack
  - matplotlib
  - jupyter

  - pip
  - pip:
     - tqdm
     - tree-sitter
     - transformers
     - scikit-learn
     - numpy
